baseURL = 'https://hrjiang.github.io/'
languageCode = 'en-us'
title = 'Hanru Jiang'

[menu]
	[[menu.main]]
		name = "Home"
		pre = "home"
		url = "/"
		weight = 1
	[[menu.main]]
		name = "Teaching"
		pre = "book"
		url = "/teaching/"
		weight = 2
	[[menu.main]]
		name = "Publications"
		pre = "list"
		url = "/publications/"
		weight = 3
	[[menu.main]]
		name = "Misc"
		pre = "coffee"
		url = "/misc/"
		weight = 4
